### ISSUE TITLE
Container Image and helm chart

### ISSUE THREAD

**Issue by klml** [it-at-m/UnicodeEingabeKiwi2#2]
Container Image and helm chart

* image ghcr.io
* helm https://github.com/it-at-m/helm-charts/

**Comment by FabianWilms** [comment]
Image is available: https://github.com/it-at-m/UnicodeEingabeKiwi2/pkgs/container/unicodeeingabekiwi2

**Comment by FabianWilms** [comment]
helm ist still missing 😉

**Comment by FabianWilms** [comment]
Internal Helm-Chart for rollout is done. Waiting for redirect of kiwi.muenchen.de, but this can be closed.
