### ISSUE TITLE
DIN 91379:2022-08

### ISSUE THREAD

**Issue by klml** [it-at-m/UnicodeEingabeKiwi2#4]
request from extern:

We are now wondering what the status of the character set is and whether the application fully fulfils the requirements of DIN 91379.

The character set of the version that is in operation at the City of Munich at https://kiwi.muenchen.de/ is apparently that of DIN SPEC 91379:2019-03 (according to the information you get when you click on the settings icon (cogwheel) in the top right-hand corner).

The DIN SPEC was replaced by DIN 91379:2022-08 in August 2022.

Although the two do not differ very much in terms of the character set, I wanted to ask whether the application basically supports the full scope of DIN 91379 (or whether an adaptation is planned).

**Comment by FabianWilms** [comment]
From https://www.din.de/de/mitwirken/normenausschuesse/nia/veroeffentlichungen/wdc-beuth:din21:353496133:

> ## Änderungsvermerk
> 
> Gegenüber DIN SPEC 91379:2019-03 wurden folgende Änderungen vorgenommen: 
> 
> **a)** Bezug zum Unicode-Standard Version 13 anstatt Version 9; 
> **b)** Begriff "Schriftzeichen" im Titel geändert in "Zeichen und definierte Zeichensequenzen"; 
> **c)** neue Absätze mit Zwischenüberschrift im Abschnitt Einleitung hinzugefügt: "Unicode Normalform C in diesem Dokument"; 
> **d)** Abschnitt 2 "Normative Verweisungen" aktualisiert; 
> **e)** neue Begriffe in Abschnitt 3 "Begriffe" aufgenommen; 
> **f)** Begriffsdefinition für "Kombinierendes diakritisches Zeichen" entsprechend Aussagen aus dem Unicode-Standard erweitert; 
> **g)** normative Aussagen zur Konformität von IT-Verfahren in den neuen Abschnitt 4 verschoben und ergänzt um Aussagen zu Normalform C (NFC) und UTF-8; 
> **h)** drei normative Zeichen im Abschnitt 5.1 "Lateinische Buchstaben" (für alle Namen) neu aufgenommen: - LATIN SMALL LETTER E WITH MACRON WITH COMBINING VERTICAL LINE ABOVE (U+0113,U+030D); - LATIN SMALL LETTER O WITH MACRON WITH COMBINING VERTICAL LINE ABOVE (U+014D,U+030D); - LATIN SMALL LETTER E WITH MACRON AND ACUTE (U+1E17); 
> **i)** Abschnitt 5.6 (normativ) "Veraltete Schriftzeichen" neu aufgenommen; 
> **j)** neue Kennzeichnung der Buchstaben in Tabelle 9 "Abbildung lateinischer Buchstaben auf Grundbuchstaben analog ICAO", zu denen ICAO keine Aussage trifft, siehe Abschnitt 6 (normativ); 
> **k)** zwei informative Zeichen im Anhang A.4 "Nicht-Buchstaben E1" (vor allem für Namen juristischer Personen und für Produktnamen) neu aufgenommen: - PRIME (U+2032); - DOUBLE PRIME (U+2033); 
> **l)** Anhang B (informativ) "Basiszeichen und diakritische Zeichen für lateinische Buchstaben" neu aufgenommen; 
> **m)** die meisten digitalen Anhänge umbenannt – Versionsangaben befinden sich nun innerhalb der Datei, nicht mehr im Dateinamen; 
> **n)** Änderungen am digitalen Anhang D mit der tabellarischen Übersicht aller Zeichen: - im Dateiformat .ods ausgeliefert anstatt .xlsx; - deutschsprachige Spaltenüberschriften verwendet; - neue Spalten "NFD-Basis" und "NFD-Diakritika"; 
> **o)** Änderungen am digitalen Anhang E mit der Abbildung auf Legacy Codepages: - im Dateiformat .ods ausgeliefert anstatt .xlsx; - erweitert um die Legacy Codepage String.Latin 1.1.1; - das Mapping von vier Zeichen, die auf dem Buchstaben Ezh basieren, entsprechend der normativen Abbildung aus Abschnitt 6 von "Y" zu "Z" korrigiert; - Mappings für griechische und kyrillische Buchstaben entfernt, da sie mittels aktuell gültiger ISO-Transliterationen in die lateinische Schrift überführt werden müssen; 
> **p)** Anhang F (informativ) "Abbildung von Legacy Codepages" neu aufgenommen; 
> **q)** Literaturhinweise aktualisiert; 
> **r)** redaktionelle Anpassungen vorgenommen.

**Comment by FabianWilms** [comment]
It seems like only

> a) Bezug zum Unicode-Standard Version 13 anstatt Version 9;

and

> h) drei normative Zeichen im Abschnitt 5.1 "Lateinische Buchstaben" (für alle Namen) neu aufgenommen: - LATIN SMALL LETTER E WITH MACRON WITH COMBINING VERTICAL LINE ABOVE (U+0113,U+030D); - LATIN SMALL LETTER O WITH MACRON WITH COMBINING VERTICAL LINE ABOVE (U+014D,U+030D); - LATIN SMALL LETTER E WITH MACRON AND ACUTE (U+1E17);

are relevant changes regarding the topicality of this application. 

---

The first should be given as the readme states:

> Für die Zerlegung eines Unicode-Strings in sogenannte Grapheme wird ein NPM-Modul benutzt, das die Zerlegung für **Unicode 13** unterstütz: [...]

The latter can be checked by looking at https://github.com/it-at-m/UnicodeEingabeKiwi2/blob/master/frontend/public/model/stringlatin-v2.xml

- LATIN SMALL LETTER E WITH MACRON WITH COMBINING VERTICAL LINE ABOVE (U+0113,U+030D);
- LATIN SMALL LETTER O WITH MACRON WITH COMBINING VERTICAL LINE ABOVE (U+014D,U+030D);
- LATIN SMALL LETTER E WITH MACRON AND ACUTE (U+1E17);

are all currently missing, but can be simply added to the xml.

**Comment by FabianWilms** [comment]
PR created. I think we should also consider 

- cleaning up this repository (the API-GW Part is not needed anyway)
- creating a deployment-pipeline here on github
- hosting it directly on github pages?
- update all dependency-versions

I will create seperate issues for this.

**Comment by FabianWilms** [comment]
I tested the charset of KIWI against [https://github.com/String-Latin/DIN-91379-Characters-and-Sequences/blob/main/latin\_list\_search\_form\_1.3.txt](https://github.com/String-Latin/DIN-91379-Characters-and-Sequences/blob/main/latin_list_search_form_1.3.txt): We now have all characters of DIN-91379:2022-08.

The hosted Version available under kiwi.muenchen.de was also updated.
